### ISSUE TITLE
Bayes Classifier Log Probability

### ISSUE THREAD

**Issue by mrene** [NaturalNode/apparatus#7] opened 2014-05-22 15:55 UTC
I was looking at bayes_classifier.js and noticed that probabilityOfClass() seems to not return a log probability, because of that last line in the function:

```
// p(C) * unlogging the above calculation P(X|C)
prob = (this.classTotals[label] / this.totalExamples) * Math.exp(prob);
```

However, in getClassifications(), the probabilities are substracted rather than divided. Am I misunderstanding something or is it a bug?

```
return labels.sort(function(x, y) {return y.value - x.value});
```

Thanks
Mathieu

**Comment by mamaral** [comment] 2015-05-10 16:07
I know this is a year old, but is there any news on this at all? I'm seeing some interesting results with simple test data and I fear this may be one of the causes.

**Comment by mamaral** [comment] 2015-05-11 13:32
Looking at this again - the subtraction is used in the *sorting* of the calculated probabilities, *not in the actual calculations*, so it appears to me that specifically is likely not an issue.

**Comment by DrDub** [comment] 2016-11-04 01:41
This is correct, the sort is done to pick the class with the highest probability value. 

Subtracting numbers is a fast way of implementing a numeric compare function.

I will close this, but feel free to re-open it if you find anything else.

**Closed by DrDub** 2016-11-04 01:41 UTC
